### ISSUE TITLE
home assistatnt menu appears twice when choosing configurator

### ISSUE THREAD

**Issue by rafiw** [home-assistant/hassio-addons#1063]
as seen in the picture
it only happens with this addon
reproduces on chrome on android and chrome on windows 10
![hass_bug](https://user-images.githubusercontent.com/3034707/74109360-48ac2500-4b8b-11ea-9995-9aa713078bbe.jpg)

**Comment by frenck** [comment]
Are you using an iframe for adding it to the menu?

**Comment by rafiw** [comment]
yes this is my configuration
```
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: 
```
