### ISSUE TITLE
No certificate obtained, no logs

### ISSUE THREAD

**Issue by richard-parker** [home-assistant/hassio-addons#1086]
Hi,

I'm running a clean install of Home Assistant (HassOS 3.10). I've just installed the Let's Encrypt add-on, and set it up for DNS challenge against Cloudflare. The config is as follows:

```
email: [redacted@redacted.com]
domains:
  - [redacted.domain.com]
certfile: fullchain.pem
keyfile: privkey.pem
challenge: dns
dns:
  provider: dns-cloudflare
  cloudflare_api_token: [redacted]
```

(I have tried both auth options for Cloudflare, and neither work by the way.)

Starting the add-on, I get the following log output:

```
[14:43:43] INFO: Selected DNS Provider: dns-cloudflare
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-cloudflare, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for [redacted.domain.com]
Cleaning up challenges
/data/dnsapikey: dns_cloudflare_email and dns_cloudflare_api_key are not needed when using an API Token
```

It's difficult to diagnose what's going on here. The add-on states that debug information is logged into **/var/log/letsencrypt**, but that folder and the file **letsencrypt.log** don't exist.

The system log isn't much help either.

Any ideas where to start digging for further debug information?

Thanks,

Rik.
