### ISSUE TITLE
Letsencrypt V4.6 new error DNS_PROVIDER: unbound variable

### ISSUE THREAD

**Issue by borpin** [home-assistant/hassio-addons#1104]
ref #1086 

Error
```
[21:04:24] INFO: Selected DNS Provider: dns-cloudflare
[21:04:24] INFO: Use propagation seconds: 60
/run.sh: line 88: DNS_PROVIDER: unbound variable
```
Config
```
email: xxx@gmail.com
domains:
  - hassio.mydomain.net
certfile: fullchain.pem
keyfile: privkey.pem
challenge: dns
dns:
  provider: dns-cloudflare
  cloudflare_email: xxxx@gmail.com
  cloudflare_api_key: xxx
```

I have created a new token, which, AIUI should not need the email as well and updated the config to use the `cloudflare_api_token`. Same error.
