### ISSUE TITLE
Homematic OCCU sends no devices to HA - Possible wrong documentation

### ISSUE THREAD

**Issue by xasz** [home-assistant/hassio-addons#1144]
##The Problem
The OCCU is configured with The Homematic PI Mod from ELV. 
The Installation is a clean HASSIO with the OCCU Addon.
The device (HM-PB-6-WM55)  is teached in the occu and appears under devies in the OCCU, but does not appear in ha.

##Addon-Configuration
The Configuration of the Addon is copied from the Readme:
```
rf_enable: true
wired_enable: false
hmip_enable: false
rf:
  - type: CCU2
    device: /dev/ttyAMA0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false
```

Network are set to:

> 2000/tcp | 2000 | HomematicWire xmlrpc (Extern)
> 2001/tcp | 2000| Homematic xmlrpc (Extern)
> 2010/tcp | 2000| HomematicIP xmlrpc (Extern)
> 80/tcp | 2000| ReGaHss Webinterface (Not required for Ingress)

##Configuration YAML
```
homematic:
  interfaces:
    rf:
      host: core-homematic
      port: 2001
    wired:
      host: core-homematic
      port: 2000
    hmip:
      host: core-homematic
      port: 2010
    group:
      host: core-homematic
      port: 9292
      path: /groups
```

I have read a lot in forums and i am not sure, if the examples in the Readme are just old and cannot work or if there any other problem.

**Comment by Nokius** [comment]
This section looks fish to me
~~~~
Network are set to:

    2000/tcp | 2000 | HomematicWire xmlrpc (Extern)
    2001/tcp | 2000| Homematic xmlrpc (Extern)
    2010/tcp | 2000| HomematicIP xmlrpc (Extern)
    80/tcp | 2000| ReGaHss Webinterface (Not required for Ingress)


~~~~
should be like this 
~~~~
Network are set to:

    2000/tcp | 2000 | HomematicWire xmlrpc (Extern)
    2001/tcp | 2001| Homematic xmlrpc (Extern)
    2010/tcp | 2010| HomematicIP xmlrpc (Extern)
    80/tcp | 980| ReGaHss Webinterface (Not required for Ingress)


~~~~

**Comment by EmpireElement** [comment]
I have the exact same issue. I just setup HASS.IO on a rapberry Pi 3 B+ this week and installed the HomeMatic CCU addon today.I am using the HmIP-RFUSB dongle to connect to my devices. I didn't configure anything else yet.

I have a homematic ip Key Ring Remote Control (HmIP-KRC4) setup within the OCCU addon and have sucessfully tested it with a progamm within the OCCU. But the device does not show up in home assistant.

Interestingly the firewall setting within the OCCU seems to be set to block all ports and cannot be updated via the UI. I don't know if this is just something visual or if the settings are currently broken.

##Addon-Configuration
```
rf_enable: false
wired_enable: false
hmip_enable: true
rf:
  - type: CCU2
    device: /dev/ttyAMA0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false
```

Network set to:
```
2000/tcp | 2000 | HomematicWire xmlrpc (Extern)
2001/tcp | 2001| Homematic xmlrpc (Extern)
2010/tcp | 2010| HomematicIP xmlrpc (Extern)
80/tcp | 80| ReGaHss Webinterface (Not required for Ingress)
```

##Configuration YAML

```
homematic:
  interfaces:
    rf:
      host: core-homematic
      port: 2001
    wired:
      host: core-homematic
      port: 2000
    hmip:
      host: core-homematic
      port: 2010
    group:
      host: core-homematic
      port: 9292
      path: /groups
```

Could you please help?
