### ISSUE TITLE
whitelist_external_dirs not a directory @ data

### ISSUE THREAD

**Issue by sp2003** [home-assistant/hassio-addons#1186]
hi
I have a problem with the configuration.yaml configuration.
HW is a Raspberry Pi3+ , OS raspbian buster Lite and installation with supervised mode
I need to read some json files from a remote folder mounted in the homeassistant directory (/ usr / share / hassio / homeassistant / solardata) therefore in / etc / fstab I added a line 
```'//192.168.0.140/PiShare /usr/share/hassio/homeassistant/solardata       cifs    _netdev,username=pi,password=PASSWORD,file_mode=0777,dir_mode=1777     0       0```

in configuration.yaml I put
```
homeassistant:
  whitelist_external_dirs:
    - /usr/share/hassio/homeassistant/solardata
```
When I start the configuration check, I get
`Invalid config for [homeassistant]: not a directory @ data['whitelist_external_dirs'][0]. Got '/solardata'. (See /config/configuration.yaml, line 16).`
line 16 is 
`homeassistant:`
Obviously the remote folder is properly mounted and browserable.

how can i solve?
this is part of the configuration.yaml
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  whitelist_external_dirs:
    - /usr/share/hassio/homeassistant/solardata
sensor:
  - platform: file
    file_path: /solardata/mN_LIVEMEMORY.json
    name: ConsumiTotali
    value_template: '{{ value_json["Consumi totali2"] }}'
    unit_of_measurement: 'W'
    scan_interval: 5
```
