### ISSUE TITLE
IPv6 URL option for DuckDNS is not working

### ISSUE THREAD

**Issue by mattclar** [home-assistant/hassio-addons#1188]
When I put a url in either ipv4 or ipv6 options I get a KO response from duckdns.
My guess  is that it seems as though maybe there is a stray quote getting added into the curl command
Although I cant confirm this if I run the curl commands in cmd i get the following result.

`C:\Users\mattc>curl -s "https://www.duckdns.org/update?domains=arthurst.duckdns.org&token=b32d1f2a-f4bc-4224-8801-21674b4ee898&ip=103.216.191.107&ipv6=2404:e80:4353::1002&verbose=true"
OK
103.216.191.107
2404:e80:4353::1002
NOCHANGE
C:\Users\mattc>curl -s "https://www.duckdns.org/update?domains=arthurst.duckdns.org&token=b32d1f2a-f4bc-4224-8801-21674b4ee898&ip='103.216.191.107'&ipv6='2404:e80:4353::1002'&verbose=true"
KO`

This is my config:
```
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: b32d1f2a-f4bc-4224-8801-21674b4ee898
domains:
  - arthurst.duckdns.org
seconds: 300
ipv4: 'https://ipv4.wtfismyip.com/text'
```
