### ISSUE TITLE
RPC Shutdown config does not support !secrets

### ISSUE THREAD

**Issue by circa1665** [home-assistant/hassio-addons#1202]
Would be great if the RPC Shutdown addon config would support secrets:

So instead of:

computers:
 - alias: test-pc-1
    address: 192.168.0.1
    credentials: user%password
    delay: 0

You could have: 

computers:
  - alias: test-pc-1
    address: !secret test-pc-1-ip
    credentials: !secret test-pc-1-creds
    delay: 0

**Comment by baldfox** [comment]
I believe this should be kept active.

**Comment by Fonta** [comment]
Addon indeed doesn't support !secret. Should indeed be kept active.

**Comment by baldfox** [comment]
should still be kept active.

**Comment by Fonta** [comment]
should still be kept active.

**Comment by Fonta** [comment]
@frenck is this something you can have a go at?

**Comment by frenck** [comment]
No, and please don't randomly pull in people by mentions. Thanks 👍

**Comment by circa1665** [comment]
Thanks for trying @Fonta

**Comment by Fonta** [comment]
Yeah well... I'm giving this a very small chance of ever getting adjusted.

**Comment by ludeeus** [comment]
Are you sure it does not work?

Remember to quote the strings for the secrets.
I tested it now with this and it does seem to work:

```yaml
computers:
  - alias: test-pc
    address: "!secret prctestip"
    credentials: "!secret prccreds"
```

I do not have any windows machines to actually test it against but the logs indicate that the secrets are indeed in use:

```txt
[20:10:48] INFO: Read alias: test-pc
[20:10:49] INFO: Shutdown test-pc -> 192.192.192.192
```

**Comment by Fonta** [comment]
No idea, I'll test it later.

**Comment by Fonta** [comment]
Tested it and indeed if you use quotes, it works.
```yaml
computers:
  - alias: WS
    address: 192.168.1.5
    credentials: '!secret rpc_shutdown_creds'
    delay: 0
    message: Home Assistant is shutting down this PC.
```
