### ISSUE TITLE
Configure Nginx to forward real IP to Home Assistant

### ISSUE THREAD

**Issue by eroji** [home-assistant/hassio-addons#1242]
I enabled the Nginx addon and it's working with my own custom cert over HTTPS,  however, I am not quite clear on how to configure Nginx to forward the real IP to Home Assistant. I tried putting the config lines in a .conf in the share path as well as putting it in a nginx_proxy_default.conf. Neither works and Home Assistant still logs the IP as 172.x.x.x.

Here is my Nginx addon config:
```
domain: assistant.example.com
certfile: fullchain.pem
keyfile: privkey.pem
hsts: max-age=31536000; includeSubDomains
cloudflare: false
customize:
  active: true
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
```

The custom Nginx config lines:
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Host $remote_addr;
real_ip_header X-Real-IP;
real_ip_recursive on;
```

I can shell into the proxy container and see /etc/nginx.conf does reference include the added conf file, but it does not go into the / path server block.
