### ISSUE TITLE
cert created with letsencrypt unseen/unused by nginx proxy add-on

### ISSUE THREAD

**Issue by edgimar** [home-assistant/hassio-addons#1326]
I am using HassOS 3.13 on a RPi 4B, and have first installed, configured, and run the let's encrypt add-on with this config (using corrected email, token, etc.):
```
email: myemail@example.com
domains:
  - ha.mydomain.com
certfile: fullchain.pem
keyfile: privkey.pem
challenge: dns
dns:
  provider: dns-cloudflare
  cloudflare_api_token: MY_TOKEN
```
This works, and the cert and key files are generated.  This can be confirmed via the SSH add-on that they exist in /ssl and their timestamps correspond to when the add-on was started.  The add-on's log also confirms that it was successful.

If I now install the nginx proxy add-on, with this config:
```
domain: ha.mydomain.com
certfile: fullchain.pem
keyfile: privkey.pem
hsts: max-age=31536000; includeSubDomains
cloudflare: false
customize:
  active: false
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
```
then after starting the add-on, the log-file shows that a self-signed cert is generated, and the previously created Let's Encrypt cert is not used.  It is my understanding that this cert should be used if it is available, and that the self-signed cert should not be generated.

If it matters at all, my network config is that I have cloudflare DNS pointing (not proxied -- just a plain old "DNS only" A entry) to my router's IP, which forwards port 9999 to 443 of the Pi.
