### ISSUE TITLE
DuckDNS config won't save

### ISSUE THREAD

**Issue by aidenmitchell** [home-assistant/hassio-addons#1328]
I can't save the config for DuckDNS, it throws an error.
``` Failed to save addon configuration, not a valid value for dictionary value @ data['options'] ```

**Comment by frenck** [comment]
Could you please share you configuration you are trying to save? (please obfuscate the URL & Token).

**Comment by Skeletorjus** [comment]
Getting the same error.

Config:
```
lets_encrypt:
  accept_terms: false
  certfile: fullchain.pem
  keyfile: privkey.pem
token: xxxxxxxxxxxxxxxxxxxx
domains:
  - xxxxxxxx.duckdns.org
seconds: 300
```

Error:

`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'lets_encrypt': {'accept_terms': False, 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem'}, 'token': ' xxxxxxxxxxxxxxxxxxxx', 'domains': ['xxxxxxxx.duckdns.org'], 'seconds': 300}
`

**Comment by lustefaniak** [comment]
That happens even with default configuration, just change and undo the change so `Save` is enabled:
```
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'lets_encrypt': {'accept_terms': False, 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem'}, 'token': None, 'domains': [None], 'aliases': [], 'seconds': 300}
```

**Comment by outworlder** [comment]
The documentation on the web says you need to leave out ".duckdns.org" but you actually can't. If you remove it then it gives the error above.

The documentation in the integration itself is fine.

**Comment by uzairfarooq** [comment]
Facing the same issue. Did anyone got a solution?

I think the problem is the capital 'F' in `'accept_terms': False`. It automatically gets converted to capital F

**Comment by uzairfarooq** [comment]
Fixed this by copying the config from their documentation. It's strange because the config I was adding was exactly the same. I suspect there might be some hidden character in their default configuration which is causing the validation to fail.

Just copy the following configuration and try to save it, it should work:
```
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: sdfj-2131023-dslfjsd-12321
domains:
  - my-domain.duckdns.org
aliases: []
seconds: 300
```
