### ISSUE TITLE
Mosquitto broker SSL error

### ISSUE THREAD

**Issue by tux240** [home-assistant/hassio-addons#1412]
Hi,

I'm trying to enable Mosquitto broker with encrypted connection on 8883 port  but get this error on logs :
```
New connection from 192.168.1.1 on port 8883.
OpenSSL Error: error:1408F09C:SSL routines:ssl3_get_record:http request
Socket error on client <unknown>, disconnecting.
```

Is there any configuration to change on the letsEncrypt plugin ?
```
email: contact@xxx.com
domains:
  - home-assistant.xxx.com
certfile: fullchain.pem
keyfile: privkey.pem
challenge: http
dns: {}
```

Here is my mosquitto config : 
```
logins:
  - username: mqtt
    password: 'xxx'
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: true
```

Thanks for your help.
