### ISSUE TITLE
DuckDNS - Improve Log Output

### ISSUE THREAD

**Issue by thedoginthewok** [home-assistant/hassio-addons#1430]
The ipv4 and ipv6 options do not work for me and I'm having a hard time finding out why.

Config:
```yaml
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: mytoken
domains:
  - mydomainname.duckdns.org
aliases: []
seconds: 300
ipv4: 'https://ipv4.text.wtfismyip.com/'
ipv6: 'https://ipv6.text.wtfismyip.com/'
```

Log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[23:51:14] INFO: KO
# INFO: Using main config file /data/workdir/config
Processing thedoginthewok.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Sep 12 20:50:25 2020 GMT Certificate will not expire
(Longer than 30 days). Skipping renew!
```

"[23:51:14] INFO: KO" is the response of the curl call that updates the ip addresses and this is only returned, if something wrong is in the ipv4 or ipv6 url parameters.

I'd suggest checking for the KO response and then logging the request URL that was used.

so "if respone is KO"
```shell
bashio::log.warning "https://www.duckdns.org/update?domains=${DOMAINS}&token=${TOKEN}&ip=${ipv4}&ipv6=${ipv6}&verbose=true"
```

This would give a hint as to what went wrong, when trying to update the IPs.

I've tried modifying the addon and installing it as a local version, but I've had no success.
