### ISSUE TITLE
MariaDB won't start after upgrade to 2.2.1

### ISSUE THREAD

**Issue by danikuci1** [home-assistant/hassio-addons#1551]
## Environment

- Add-on with the issue: MariaDB
- Add-on release with the issue:  2.2.1
- Last working add-on release (if known):  2.1.2
- Operating environment (OS/Supervised):  
HassOS 4.12
Production
Supervisor Version 235

## Problem-relevant configuration

```yaml
databases:
  - homeassistant
logins:
  - username: hass
    host: '%'
    password: MySuperSecretPassword
rights:
  - username: hass
    host: '%'
    database: homeassistant
    grant: ALL PRIVILEGES ON

```

## Traceback/Error logs

```txt
20-08-26 17:49:45 INFO (SyncWorker_1) [supervisor.docker.addon] Start Docker add-on homeassistant/armv7-addon-mariadb with version 2.1.2
20-08-26 17:49:52 INFO (MainThread) [supervisor.services.modules.mysql] Set core_mariadb as service provider for MySQL
20-08-26 17:49:54 INFO (SyncWorker_0) [supervisor.docker.interface] Stop addon_core_mariadb application
20-08-26 17:50:03 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_core_mariadb application
20-08-26 17:50:03 ERROR (MainThread) [supervisor.utils] Can't execute update while a task is in progress
20-08-26 17:50:03 ERROR (MainThread) [supervisor.utils] Can't execute cleanup while a task is in progress
20-08-26 17:50:03 INFO (MainThread) [supervisor.addons] Add-on 'core_mariadb' successfully updated
20-08-26 17:50:03 WARNING (MainThread) [supervisor.addons.validate] Unknown options host
20-08-26 17:50:03 WARNING (MainThread) [supervisor.addons.validate] Unknown options host
20-08-26 17:50:03 WARNING (MainThread) [supervisor.addons.validate] Unknown options grant
20-08-26 17:50:03 ERROR (SyncWorker_0) [supervisor.docker] Can't create container from addon_core_mariadb: 404 Client Error: Not Found ("No such image: homeassistant/armv7-addon-mariadb:2.2.1")

```

## Additional information

from the homeassistant.log file:

`ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'core-mariadb' (-3)")`

sql connection url from configuration.yaml
`
mysql://192.168.1.18:MySuperSecretPassword@core-mariadb/homeassistant
`

**Comment by RuBiCK** [comment]
@danikuci1 I have the same issue. Did you found a solution?

**Comment by danikuci1** [comment]
not exactly. apparently at some point the configuration parameters changed, although i couldnt find any documentation of it, the errors are pretty clear:  `host` and `grant` no longer belong in the configuration.

however, this didn't solve my problem. i had to reinstall a new DB to get it to work, which makes me think that maybe there was some migration process or something that didn't run successfully - though this is pure speculation. 

so, bottomline, i fixed it by abandoning it and creating it new.

here is my new configuration:
```
databases:
  - homeassistant
logins:
  - username: hass
    password: MySuperSecretPassword
rights:
  - username: hass
    database: homeassistant

```
