### ISSUE TITLE
 Integration 'ssl_certificate' not found.

### ISSUE THREAD

**Issue by SM-26** [home-assistant/hassio-addons#1612]
## The problem

When trying to set up DuckDNS for the first time, [following this guide](https://techtechandmoretech.com/guides/hass-duckdns/)
I can see the files that DuckDNS add on has created in the ssl folder, but after editing the config file, I can't validate it.

## Environment

Raspberry pi 4, 4gb rev 1.2,
Boot from ssd
 hassos_rpi4-64-5.2.img

- Add-on with the issue: DuckDns
- Add-on release with the issue:  1.12.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  Hass.io

## Problem-relevant configuration

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
base_url: https://MY-ADDR.duckdns.org
ssl_certificate: /ssl/fullchain.pem
ssl_key: /ssl/privkey.pem
```

## Traceback/Error logs

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:326
Integration: Hass.io (documentation, issues)
First occurred: 0:53:48 (1 occurrences)
Last logged: 0:53:48

Component error: ssl_certificate - Integration 'ssl_certificate' not found. Component error: base_url - Integration 'base_url' not found. Component error: ssl_key - Integration 'ssl_key' not found.
```

## Additional information
![image](https://user-images.githubusercontent.com/39513660/95264978-f1a14180-0838-11eb-9c3e-95e48433dbaa.png)

**Comment by ludeeus** [comment]
Your configuration is wrong.

```yaml
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```

Closing as this is a configuration issue and not an issue with the addon.
