### ISSUE TITLE
DuckDNS via TP-link doesnt work

### ISSUE THREAD

**Issue by MerijnKo** [home-assistant/hassio-addons#1639]
## The problem
 I want to be able to access home assistant from outside my home network. i followed all the steps; make a domain on duckdns.org and put the relevant information in the configuration, as shown below, then i port forwarded port 443 external to port 8123 internal with the ip adress of my raspberry/home assistant. if i type my domain.duckdns.org after completing all of it (first restarted HA) i cant access HA any more. Than i delete the configuration and port forwarding to be able to access my HA again. The only thing i think is the problem is that i have an TP-link deco m9 plus, which extends my wifi signal with a mesh network. I have three of them around the house and one of them acts as an router, this one is connected to my main router. All of my systems are connected to this TP-link. I am doing the port forwarding via the TP-Link. hard to explain how it exactly works, but this is a link from the product: https://www.tp-link.com/nl/home-networking/deco/deco-m9-plus/
So my ip adress from the main router is 192.168.2.xxx and from the TP-Link its 192.168.68.xxx

Anybody else having some kind of same problem and has a solution or just some kind of advice?
Thanks to all of you!
## Environment

- Add-on with the issue: DuckDNS
- Add-on release with the issue: 1.12.1
- Last working add-on release (if known): -
- Operating environment (OS/Supervised): Raspberry pi

## Problem-relevant configuration

Configuration in add-on 
```yaml
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: my personal token
domains:
     -my domain.duckdns.org
aliases: []
seconds: 300
```
Configuration in configuration.yaml
```yaml
http: 
    base_url: my domain.duckdns.org
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem
```

## Traceback/Error logs

```txt

```
