### ISSUE TITLE
Duck DNS returns "KO" after updating duckdns add-on to 1.12.2

### ISSUE THREAD

**Issue by Kars-de-Jong** [home-assistant/hassio-addons#1657]
## The problem
After updating to version 1.12.2 of the duckdns add-on, the log shows "KO" every 5 minutes. This means the update failed.
Note that I do not have the `ipv4` or `ipv6` settings configured (they are both unset).

## Environment

- Add-on with the issue: duckdns
- Add-on release with the issue: 1.12.2
- Last working add-on release (if known): 1.12.1
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

The configuration of the add-on:
```yaml
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: xxxxxxxxxx
domains:
  - xxx.duckdns.org  
aliases: []
seconds: 300

```

## Traceback/Error logs

```txt
[17:14:09] INFO: KO
...
[17:19:12] INFO: KO
```

## Additional information
It also logs "KO" when I use the URL option for the `ipv4` setting. Ditto for the `ipv6` setting.
It also logs "KO" when I hard code the IP address in the `ipv4` setting.
I can login just fine to duckdns.org, which shows the same token as is used in the config.
The problematic commit seems to be #1654 .
