### ISSUE TITLE
Can git pull add-on be called from automation to sync files

### ISSUE THREAD

**Issue by shortbloke** [home-assistant/hassio-addons#360]
I'm using the git pull add-on which has been setup to sync files every 5 mins. I'd prefer to change this so that it syncs only on a successful TravisCI build rather than risk pulling a broken configuration.

With the automation:
```
- id: a_config_update
  alias: Update config HASS if travis build is successfull
  trigger:
    - platform: state
      entity_id: sensor.shortblokehome_assistant_config_last_build_id
  condition:
    - condition: state
      entity_id: sensor.shortblokehome_assistant_config_last_build_state
      state: 'passed'
  action:
    - service: hassio.addon_stop
      data: 
        addon: "core_git_pull"
    - service: hassio.addon_start
      data: 
        addon: "core_git_pull"
    - delay: 0:01
    - service: hassio.addon_stop
      data: 
        addon: "core_git_pull"
```
I ensure the add-on is stopped, start it, if there are changes they will sync (so long as it takes less than 1min), then the add-on is stopped again.

I'd prefer to have the service running and be able to poke it to start the sync to save the stopping and starting and the arbitrary 1min delay.

Can this be done via `hassio.addon_stdin` ?
