### ISSUE TITLE
Unable to run only in ssl mode.

### ISSUE THREAD

**Issue by niemyjski** [home-assistant/hassio-addons#405]
I'm running duckdns with ssl configured on the latest version of hass.io. I set plain mode and plain web sockets to false and configured the settings to enable ssl. I then setup the mqtt component to point to port 8883 (what ever the default port starting with 8xxx is) and configured the user name and password.

```
mqtt:
  broker: core-mosquitto
  port: 8883
  username: !secret mqtt_username
  password: !secret mqtt_password
```

https://github.com/niemyjski/home-assistant/blob/master/config/mqtt.yaml

When you do this... you get a ton of the following errors like this in the add-on logs:

```
1536781640: OpenSSL Error: error:140260FC:SSL routines:ACCEPT_SR_CLNT_HELLO:unknown protocol
1536781640: Socket error on client <unknown>, disconnecting.
1536781640: New connection from 172.30.32.1 on port 8883.
1536781730: Client <unknown> has exceeded timeout, disconnecting.
1536781730: Socket error on client <unknown>, disconnecting.
```

But there are no errors listed in the client side (hass.io system log)
