### ISSUE TITLE
Configurator URL after ugrade to 3.0

### ISSUE THREAD

**Issue by nealeydee** [home-assistant/hassio-addons#562]
Documentation provides a way to add the Configurator iFrame to the sidebar in HomeAssistant. I have had this working since I set up HomeAssistant.

Since the upgrade to v 3.0 of configurator, the url no longer works.

I have had some success in using a URL that I discovered... something like this:

/api/hassio_ingress/TNLixycE****zi2d****bpFJWF****2e240****f6-4/

but this is not documented?
How should one set this up now?

**Comment by scottyphillips** [comment]
The standard Home Assistant documentation for integrating the side panel is now out of date so yes it would be useful if someone could document how to restore side panel access..

**Comment by DoctorOctagonapus** [comment]
That hash in the URL apparently changes either randomly or every time the frame is loaded, so you can't even embed that URL. Is there any way of embedding it at all?

**Comment by ronmichel** [comment]
Using the url /hassio/ingress/core_configurator works but it opens the another sidepanel inside the frame. Maybe add an option to deactivate the sidepanel in the configurator ingress page would be a fix?

**Comment by cogneato** [comment]
It's still being worked on, and the plan is to have it automatically added using a toggle or option within the addon config, but here is the config you need. You also need supervisor 159.

```
panel_custom:
  - name: hassio-main
    sidebar_title: Configurator
    sidebar_icon: hass:settings
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
```
<https://github.com/home-assistant/home-assistant-polymer/pull/3085>
