### ISSUE TITLE
Fix Route53 support in Let's Encrypt 

### ISSUE THREAD

**Issue by pickerin** [home-assistant/hassio-addons#956]
Re-opening https://github.com/home-assistant/hassio-addons/issues/754 issue as it appears to not be fixed.

After configuration, the add-on is passing "--dns-route53-credentials /data/dnsapikey" to certbot which is an invalid option.

@imduffy15 copied the addon code and created a complete fix here:
https://github.com/imduffy15/hassio-addons/tree/master/letsencrypt

This is with Home Assistant 0.103.5.

**Comment by aapit** [comment]
I can confirm these exact symptoms on HA `0.104.0`, in my case on `hass.io`.

**Comment by Zapfmeister** [comment]
Please check if it works with the latest version and provide feedback

**Comment by gitolicious** [comment]
I thought the same, but digging into the code I found out it's just a case of insufficient documentation combined with confusing log output.

https://github.com/home-assistant/hassio-addons/blob/a5569342fb46166e3c68c5880193e94847e12e6b/letsencrypt/rootfs/etc/services.d/lets-encrypt/run#L29-L35

So the check isn't actually on your `dns.provider` to be _dns-route53_ but on the existence of AWS credentials. Add the following and you should be good to go:

```
dns:
  provider: dns-route53
  aws_access_key_id: YOURKEYHERE
  aws_secret_access_key: YOURSECRETHERE
```

**Comment by pmgledhill102** [comment]
And a note for anyone reading this. You don't include the `dns:` parent in the UI. You just put the 3 parameters
```yaml
provider: dns-route53
aws_access_key_id: YOURKEYHERE
aws_secret_access_key: YOURSECRETHERE
```
