### ISSUE TITLE
Add hibernation or suspend mode in the RPC Shutdown Hassio add-on

### ISSUE THREAD

**Issue by martusi61** [home-assistant/hassio-addons#976]
Thanks for the excellent and useful work done, but I was wondering if it was possible to add hibernation or suspend mode in the RPC Shutdown Hassio add-on.

**Comment by blacktirion** [comment]
I've looked into this in the past. I recently researched it again, and found that the command that is used in this addon (net rpc shutdown) does not support sleep/hibernation. So currently, it would not work. 

However there is the possibility to use PSExec to maybe achieve this, but it would require winexe (Linux Based PSExec). That doesn't even account for the security risk of PSExec commands. 

I'll look into this a bit further and see if it's reasonable to test this out. If not, you may want to use the following method:

[Airytec Switch Off](http://www.airytec.com/en/switch-off/faq/how-to-shutdown-computer-at-specified-time.aspx)

This software allows you to create a web api that listens for specific commands, so you could do a shell command like this:
```

switch:
  - platform: wake_on_lan
    mac: "XX-XX-XX-XX-XX-XX"
    host: 192.168.xxx.xxx
    name: Computer
    turn_off:
      service: shell_command.turn_off_computer

shell_command:
  turn_off_computer: 'curl -k http://192.168.xxx.xxx:8000/?action=System.Sleep'
```

This software even has authentication. It can/will run as a service in the background so you won't even see it.
