### ISSUE TITLE
SSL cert file location path - lets encrypt add-on

### ISSUE THREAD

**Issue by chrkoe** [home-assistant/hassio-addons#997]
Hi,

I am new to hass.io and tried the lets encrypt add-on.\
The logs from running the add-on said, that I can find my files in `/data/letsencrypt/live/hass.mydomain.de/` (`fullchain.pem` & `privkey.pem`).

I tried to add this files in my `configuration.yaml`:
```
http:
  base_url: https://hass.mydomain.de
  ssl_certificate: /data/letsencrypt/live/hass.mydomain.de/fullchain.pem
  ssl_key: /data/letsencrypt/live/hass.mydomain.de/privkey.pem
```

That didn't worked after a reload. I got errors saying, that the file is not found.
I take a look (via SSH) in some folders and found these files (from lets encrypt??) in `/ssl/`\
So I changed the config, restart, nothing is working... -> login via SSH and commented the configuration parameter. Hard-reset the RasPi 4 and I can access the web GUI via the original unsecured http port 8123.

Can you tell me how to properly use the lets encrypt add-on?

I have my own domain and configured the correct NAT rules on my opnsense firewall.
